build:
  maxIssues: 0

detekt-hint:
  UseCompositionInsteadOfInheritance:
    active: true
    yourUniquePackageName: "hello"
  LackOfCohesionMethods:
    active: true
    threshold: "0.8"
  InterfaceSegregationPrinciple:
      active: true
  OpenClosedPrinciple:
      active: true

